const demo=document.getElementById("Expert")
demo.style.backgroundColor="#2E5A88";
// demo.style.backgroundColor="#000435";//dark navy blue color
const talk=document.querySelector(".Talk")
talk.style.color="white"
talk.style.fontWeight="bold"
talk.style.paddingTop="3%"
talk.style.paddingLeft="40%"
const para=document.querySelector(".achieve")
para.innerHTML="<p>Get started today on achieving SEO goal by talking to one of our SEO expert"
para.style.color="white"
para.style.marginLeft="28%"
para.style.fontWeight="bold"
const input=document.querySelector(".input")
input.style.margin="3%"
const input1=document.getElementById("name")
input1.style.backgroundColor="#2E5A88"
input1.style.marginLeft="8%"
input1.style.marginRight="3%"
input1.style.paddingLeft="2%"
input1.style.paddingTop="1%"
const input2 =document.getElementById("phone")
input2.style.backgroundColor="#2E5A88"
input2.style.marginRight="3%"
input2.style.paddingLeft="2%"
const input3=document.getElementById("email")
input3.style.backgroundColor="#2E5A88"
input3.style.marginRight="3%"
input3.style.paddingLeft="2%"
const input4=document.getElementById("website url")
input4.style.backgroundColor="#2E5A88"
input4.style.color="white"
input4.style.paddingLeft="2%"
input4.style.paddingTop="1%"
const button=document.querySelector(".Thamilbutton")
button.style.marginLeft="43%"
button.style.marginTop="3%"
button.style.borderRadius="50px"
button.style.border="none"
button.style.paddingTop="10px"
button.style.paddingBottom="10px"
button.style.paddingRight="15px"
button.style.paddingLeft="15px"
const video=document.querySelector(".video")
video.style.marginLeft="5%"
video.style.width="550px"
const seo=document.querySelector(".seoagency")
// seo.style.width="auto"
// seo.style.height="700px"
seo.style.backgroundColor="aliceblue"
const footer=document.querySelector(".footer")
footer.style.width="auto"
footer.style.height="450px"
  footer.style.backgroundColor="#000435"
// footer.style.backgroundColor="#2E5A88"